#!/usr/bin/env bash

# Set environment variables for dev
export APP_ENV=${APP_ENV:-local}
export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-root}
export DB_NAME=${DB_NAME:-nilus_develop}
export DB_USER=${DB_USER:-nilus}
export DB_PASS=${DB_PASS:-root}

COMPOSE_BASE_FILE="./docker-compose.base.yml"
COMPOSE_FILE="dev"
TTY=""

if [ "$NILUS_ENV" == "production" ]; then
    COMPOSE="docker-compose -f $COMPOSE_BASE_FILE -f ./docker-compose.yml"
else
    # Change settings for CI
    if [ ! -z "$BUILD_NUMBER" ]; then
        COMPOSE_FILE="ci"
    	TTY="-T"
    fi

    #COMPOSE="docker-compose -f $COMPOSE_BASE_FILE -f ./docker-compose.$COMPOSE_FILE.yml"
    COMPOSE='docker-compose -f ./docker-compose.yml'
fi

APP_NAME="php"
WORKSPACE_NAME="workspace"
WORK_DIR="/var/www/laravel"
# If we pass any arguments...
if [ $# -gt 0 ];then

    # If "art" is used, pass-thru to "artisan"
    # inside a new container
    if [ "$1" == "art" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
            -w $WORK_DIR \
             $APP_NAME \
            php artisan "$@"

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm $TTY\
            -w $WORK_DIR \
            $APP_NAME \
            composer "$@"

    # If "test" is used, run unit tests,
    # pass-thru any extra arguments to php-unit
    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm $TTY\
            -w $WORK_DIR \
            $APP_NAME \
            ./vendor/bin/phpunit "$@"
	
	elif [ "$1" == "t" ]; then
        shift 1
        $COMPOSE exec \
            $APP_NAME \
            sh -c "cd $WORK_DIR && ./vendor/bin/phpunit $@"
    # If "npm" is used, run npm
    # from our node container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm $TTY\
            -w $WORK_DIR \
            $WORKSPACE_NAME \
            npm "$@"
		
    elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm $TTY\
            -w $WORK_DIR \
            $WORKSPACE_NAME \
            yarn "$@"
    else
        $COMPOSE "$@"
    fi

else
    $COMPOSE ps
fi
